require "./app/models/event"



# Event.create(title: "Aladdin and Arabian", address: "300 west Hasting", capacity: 10, description: "Come and enjoy the unique experienece of authentic arabian food perpared by chef Mohammad followed by the presentation of the disney classic Aladdin",price: 50, event_date: '20-06-2016 20:00:00', image_file: "aladdin.jpeg")

# Event.create title: "A Lion King Evening with African Cuisine", address: "19 Stanley Park West", capacity: 15, description: "We invite you to join mama patience for an evening of African cuisine prepared intrue African style. We will eat, we will dance before settelig down to the Lion King",price: 50, event_date: '21-06-2016 19:00:00', image_file:"lionking.jpeg"

# Event.create title: "Forest Gump and the Best of Southern Barbecue", address: "233, Lonsdale quay, Noth Van", capacity: 20, description: "we will be having a barbecue and you are all invited. Seafood chicken and steak prepared in a cajun way will be on the grill from 4:00 onwards. Come meet some fun people, enjoy the food and at 7:00 the main event",price: 50, event_date: '22-06-2016 20:00:00', image_file: "forrest_gump.jpeg"

# Event.create title: "Indiana Jones II and the Taste of Jordan", address: "26, Petra Avenue", capacity: 8, description: "Our food adventure this time will take us to the deepest darkest parts of the West End. Wow do we have an event for you. I have just returned from Jordan where my friends have given me a crash course in Jordanian cuisine. I would love to share this with you. There will of course be plenty of wine too. Look forward to meeting you soon. ",price: 60, event_date: '23-06-2016 18:00:00', image_file: "Indiana_jones.jpeg"

# Event.create title: "A James Bond feature with best of Britan and Russia cuisine ", address: " 200 West Berlin street, Vancouver", capacity: 10, description: "James Bond will be re knewing his old clash with our friends from the old Soviet Russia and what a way to celbrate but offerieng some traditional classics from both sides of the pacific. Britian and some Bangers and Mash, and Russia with some Borsh and Shislik. A culinary match made in heaven. Hope to see you there",price: 50, event_date: '24-06-2016 18:00:00', image_file: "james_bond.jpeg"

# Event.create title: "Euro Cup Final with French wine and delites", address: "400 Robert street, Vancouver", capacity: 20, description: "Welcome all football fans to an evening of football and everything French. For this final we will be putting on a French themed event, so where your team colors or your best French outfit and we will be serving an assorment of French wine and cheeses throughout the evening. Baguettes and the deliciousy snails will also be sampled. Look forward to seeing you there. Allez les Bleu!! ",price: 70, event_date: '25-06-2016 20:00:00', image_file: "eurocup_final.jpg"


Event.create(title:"Indiana Jones II and the Taste of Jordan", description:"OUR FOOD ADVENTURE THIS TIME WILL TAKE US TO THE DEEPEST DARKEST PARTS OF THE WEST END. WOW DO WE HAVE AN EVENT FOR YOU. I HAVE JUST RETURNED FROM JORDAN WHERE MY FRIENDS HAVE GIVEN ME A CRASH COURSE IN JORDANIAN CUISINE. I WOULD LOVE TO SHARE THIS WITH YOU. THERE WILL OF COURSE BE PLENTY OF WINE TOO. LOOK FORWARD TO MEETING YOU SOON.",movie_genre:"Action",cuisine:"Arabian",capacity: 10  ,price: 40  ,address:"26, Petra Avenue",event_date:"2016-06-20",image_file:"indiana-jones.jpg",start_time:"19:00 PM")
Event.create(title:"Kung Fu Panda and Sushi", description:"We would like to formaly invite you to the screening of Kung Fu panda and a sushi evening extradorinaire. Now you may be thinking Kung fu and Pandas are of Chinese decent- yes we know, but we really love sushi and as such we will be serving home made sushi throughout the evening. Nakamote our Japanese friend will be giving a sushi making demo before the screening of our favourite movie Kung Fu Panda. We are thouroughly looking forward to showing our Japanese friend a Canadian good time so please come join us next week for what is sure to be a great event.",movie_genre:"Animation",cuisine:"Japanese",capacity: 15  ,price: 30  ,address:"123,  Garanvile Avenue",event_date:"2016-06-21",image_file:"kung-fu-panda.jpg",start_time:"20:00 PM ")
Event.create(title:"Imitation Game and international cuisine", description:"For us computer enthusiasts Alan Turin and his Turin machine is of particular interest. He and his team were able to shorten the war by two years by cracking the enigma code. Come explore this interesting story as we watch the Oscar award winning Imatation game. We will be offereing a selection of cuisines from around the world and truly hope to bring together people of different nationalties to celebrate a united world and the birth of the computing machine.",movie_genre:"Drama",cuisine:"Traditional",capacity: 10  ,price: 35  ,address:"456, Main Street",event_date:"2016-06-24",image_file:"imitation game.jpeg",start_time:"21:00 PM")
Event.create(title:"A JAMES BOND FEATURE WITH BEST OF BRITAN AND RUSSIA CUISINE", description:"JAMES BOND WILL BE RE KNEWING HIS OLD CLASH WITH OUR FRIENDS FROM THE OLD SOVIET RUSSIA AND WHAT A WAY TO CELEBRATE BUT OFFERING SOME TRADITIONAL CLASSICS FROM BOTH SIDES OF THE PACIFIC. BRITIAN AND SOME BANGERS AND MASH, AND RUSSIA WITH SOME BORSH AND SHISLIK. A CULINARY MATCH MADE IN HEAVEN. HOPE TO SEE YOU THERE",movie_genre:"Action",cuisine:"Traditional",capacity: 15 ,price: 25  ,address:"436, 2nd Avenue",event_date:"2016-06-26",image_file:"james bond.jpeg",start_time:"19:00 PM")
Event.create(title:"FOREST GUMP AND THE BEST OF SOUTHERN BARBECUE", description:"WE WILL BE HAVING A BARBECUE AND YOU ARE ALL INVITED. SEAFOOD CHICKEN AND STEAK PREPARED IN A CAJUN WAY WILL BE ON THE GRILL FROM 4:00 ONWARDS. COME MEET SOME FUN PEOPLE, ENJOY THE FOOD AND AT 7:00 THE MAIN EVENT",movie_genre:"Drama",cuisine:"Southern",capacity: 20  ,price: 30  ,address:"321, Dawson Street",event_date:"2016-07-01",image_file:"Forrest-Gump.jpg",start_time:"20:00 PM")
Event.create(title:"ALADDIN AND ARABIAN", description:"COME AND ENJOY THE UNIQUE EXPERIENECE OF AUTHENTIC ARABIAN FOOD PERPARED BY CHEF MOHAMMAD FOLLOWED BY THE PRESENTATION OF THE DISNEY CLASSIC ALADDIN",movie_genre:"Animation",cuisine:"Arabian",capacity: 5 ,price: 50  ,address:"678, Boundry Road ",event_date:"2016-07-03",image_file:"aladdin.jpg",start_time:"21:00 PM")
Event.create(title:"A LION KING EVENING WITH AFRICAN CUISINE", description:"WE INVITE YOU TO JOIN MAMA PATIENCE FOR AN EVENING OF AFRICAN CUISINE PREPARED IN TRUE AFRICAN STYLE. WE WILL EAT, WE WILL DANCE BEFORE SETTLING DOWN TO THE LION KING",movie_genre:"Animation",cuisine:"African",capacity: 10  ,price: 30  ,address:"658, Hasting Street",event_date:"2016-07-06",image_file:"lionking.jpeg",start_time:"20:00 PM")
Event.create(title:"EURO CUP FINAL WITH FRENCH WINE AND delights", description:"WELCOME ALL FOOTBALL FANS TO AN EVENING OF FOOTBALL AND EVERYTHING FRENCH. FOR THIS FINAL WE WILL BE PUTTING ON A FRENCH THEMED EVENT, SO WHERE YOUR TEAM COLORS OR YOUR BEST FRENCH OUTFIT AND WE WILL BE SERVING AN ASSORMENT OF FRENCH WINE AND CHEESES THROUGHOUT THE EVENING. BAGUETTES AND THE DELICIOUSY SNAILS WILL ALSO BE SAMPLED. LOOK FORWARD TO SEEING YOU THERE. ALLEZ LES BLEU!!",movie_genre:"Sports",cuisine:"French",capacity: 20  ,price: 25  ,address:"657, West Pender",event_date:"2016-08-01",image_file:"eurocup_final.jpg",start_time:"19:00 PM ")
Event.create(title:"The Hangover with a Greasy Feast", description:"At the Sadeh household we love a good party and hope you do to. We invite you to the Hangover (the movie) inspired evening with a greasy feast served throughout the night. Upon entry you will receive a bottle of beer and 2 shots of Jagermeister. At 8pm we will all sit down to enjoy the feature of the evening, while burgers, hotdogs and other greasy classics are served. We have a fully stocked bar and look forward to meeting new friends. Who knows where the night will lead. Wink wink.",movie_genre:"Comedy",cuisine:"Traditional",capacity: 15  ,price: 15  ,address:"738, Drake Street",event_date:"2016-08-03",image_file:"hangover.jpg",start_time:"20:00 PM ")
Event.create(title:"Con air at Lighthouse labs", description:"For the new cohort arriving today we will be putting on this event for you. I am sure many of your are as excited as we were when we first arrived. However you will soon realise that this 50 square meter room will become home for 12+ hours a day of intensive learning. You will have daily chores, your diet will probably consist of simple fast food meals from around the hood, and your exercise will be limited to foosball. Does this lack of freedom remind you of anything? Hahahaha self invlicted yet highly benfcial incarceration. In honour of our life choices we would to theme up the place and screen Con Air. We will be serving mini Jail house meals to add some sustinece to the evening. Great jail house classics like Chili and bread, and soup and toast will be on the menu throughout the evening. After the movie we can Breakout to the bars and cause havoc around town like I am sure the senior cohort will do on Thursday.",movie_genre:"Drama",cuisine:"Traditional",capacity: 100 ,price: 0 ,address:"128, Hasting Street",event_date:"2016-06-22",image_file:"lighthouse.jpg",start_time:"19:00 PM")